# Generated by Django 5.2.1 on 2025-06-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='usuario',
            new_name='user',
        ),
    ]
